/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyDslARuntimeModule;
import org.xtext.example.mydsl.MyDslAStandaloneSetup;
import org.xtext.example.mydsl.ide.MyDslAIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyDslAIdeSetup extends MyDslAStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyDslARuntimeModule _myDslARuntimeModule = new MyDslARuntimeModule();
    MyDslAIdeModule _myDslAIdeModule = new MyDslAIdeModule();
    return Guice.createInjector(Modules2.mixin(_myDslARuntimeModule, _myDslAIdeModule));
  }
}
