/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.MyDslBStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslBStandaloneSetup extends MyDslBStandaloneSetupGenerated {
  public static void doSetup() {
    new MyDslBStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
