/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.AbstractMyDslBRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslBRuntimeModule extends AbstractMyDslBRuntimeModule {
}
