/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractMyDslBIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslBIdeModule extends AbstractMyDslBIdeModule {
}
