/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.MyDslBRuntimeModule;
import org.xtext.example.mydsl.MyDslBStandaloneSetup;
import org.xtext.example.mydsl.ide.MyDslBIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MyDslBIdeSetup extends MyDslBStandaloneSetup {
  @Override
  public Injector createInjector() {
    MyDslBRuntimeModule _myDslBRuntimeModule = new MyDslBRuntimeModule();
    MyDslBIdeModule _myDslBIdeModule = new MyDslBIdeModule();
    return Guice.createInjector(Modules2.mixin(_myDslBRuntimeModule, _myDslBIdeModule));
  }
}
