/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui;

import a.ui.internal.AActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AActivator.getInstance().getInjector(AActivator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSLA);
	}
	
}
