/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.xtext.example.mydsl.ui.tests;

import a.ui.internal.AActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDslA");
	}

}
